# Generated by Django 3.2 on 2022-06-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('postulante_id', models.AutoField(primary_key=True, serialize=False)),
                ('postulante_nombre', models.CharField(max_length=100, verbose_name='Nombre Postulante')),
                ('postulante_apellido', models.CharField(max_length=100, verbose_name='Apellido Postulante')),
                ('postulante_dni', models.CharField(max_length=15, verbose_name='DNI')),
                ('postulante_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('postulante_fecha_nacimiento', models.DateTimeField(null=True, verbose_name='Nacimiento')),
                ('postulante_genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='masculino', max_length=15)),
                ('postulante_pais', models.CharField(max_length=50, verbose_name='Pais Nacimiento')),
                ('postulante_celular', models.CharField(max_length=15)),
                ('postulante_departamento', models.CharField(max_length=50)),
                ('postulante_provincia', models.CharField(max_length=50)),
                ('postulante_direccion', models.CharField(max_length=100)),
                ('fecha_postulacion', models.DateTimeField(null=True, verbose_name='Fecha Postulación')),
                ('mes_postulacion', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=15)),
            ],
        ),
    ]
