# Generated by Django 3.2 on 2022-06-01 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academico',
            fields=[
                ('calificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('profesion', models.CharField(max_length=100, verbose_name='Profesion')),
                ('area_profesional', models.CharField(choices=[('secundaria', 'Secundaria'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('titulado', 'Titulado'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], default='universitario', max_length=15)),
                ('centro_estudios', models.CharField(max_length=50, verbose_name='Centro de Estudios')),
                ('fecha_egreso', models.DateTimeField(null=True, verbose_name='Fecha de egreso')),
                ('curso_adicional_1', models.CharField(max_length=100, verbose_name='Curso Adicional 1')),
                ('curso_adicional_2', models.CharField(max_length=100, verbose_name='Curso Adicional 2')),
                ('nivel_ingles', models.CharField(choices=[('secundaria', 'Secundaria'), ('tecnico', 'Técnico'), ('universitario', 'Universitario'), ('titulado', 'Titulado'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado')], default='universitario', max_length=15)),
                ('postulante_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.postulante')),
            ],
        ),
    ]
