# Generated by Django 3.2 on 2022-06-01 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_academico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboral',
            fields=[
                ('laboral_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Nombre Empresa')),
                ('ruc', models.CharField(max_length=25, verbose_name='RUC')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono de Empresa')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección de Empresa')),
                ('cargo_desempenho', models.CharField(max_length=100, verbose_name='Cargo')),
                ('fecha_inicio', models.DateTimeField(null=True, verbose_name='Fecha inicio')),
                ('fecha_termino', models.DateTimeField(null=True, verbose_name='Fecha termino')),
                ('descripcion_actividad', models.CharField(max_length=500, verbose_name='Descripción de Actividad')),
                ('tiempo', models.CharField(choices=[('De 0 a 1 anho', 'De 0 a 1 anho'), ('De 1 a 2 anhos', 'De 1 a 2 anhos'), ('De 2 a 3 anhos', 'De 2 a 3 anhos'), ('3 anhos a mas', '3 anhos a mas')], default='0', max_length=25)),
                ('postulante_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.postulante')),
            ],
        ),
    ]
