# Generated by Django 3.2 on 2022-06-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_laboral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=100, verbose_name='Pregunta')),
                ('nunca', models.IntegerField(default=0)),
                ('rara_vez', models.IntegerField(default=0)),
                ('a_veces', models.IntegerField(default=0)),
                ('a_menudo', models.IntegerField(default=0)),
                ('siempre', models.IntegerField(default=0)),
            ],
        ),
    ]
