# Generated by Django 3.2 on 2022-06-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psicologico',
            fields=[
                ('psicologico_id', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(default=0)),
                ('postulante_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.postulante')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.test')),
            ],
        ),
    ]
