# Generated by Django 3.2 on 2022-06-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('convocatoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('convocatoria_nombre', models.CharField(max_length=100, verbose_name='Nombre Convocatoria')),
                ('nombre_entidad', models.CharField(max_length=50, verbose_name='Entidad')),
                ('convocatoria_photo', models.ImageField(blank=True, upload_to='photos')),
                ('fecha_inicio', models.DateTimeField(null=True, verbose_name='Fecha inicio')),
                ('fecha_termino', models.DateTimeField(null=True, verbose_name='Fecha termino')),
                ('numero_vacantes', models.IntegerField(default=1)),
                ('remuneracion', models.DecimalField(decimal_places=2, max_digits=9)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=15)),
                ('empresa_convoca_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.empresa')),
            ],
        ),
    ]
