# Generated by Django 3.2 on 2022-06-01 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_convocatoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('calificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('calf_academica', models.DecimalField(decimal_places=2, max_digits=9)),
                ('calf_laboral', models.DecimalField(decimal_places=2, max_digits=9)),
                ('calf_psicologica', models.DecimalField(decimal_places=2, max_digits=9)),
                ('calf_asertividad', models.DecimalField(decimal_places=2, max_digits=9)),
                ('calf_autoestima', models.DecimalField(decimal_places=2, max_digits=9)),
                ('calf_comunicacion', models.DecimalField(decimal_places=2, max_digits=9)),
                ('calf_tomadecision', models.DecimalField(decimal_places=2, max_digits=9)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=15)),
                ('convocatoria_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.convocatoria')),
                ('postulante_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.postulante')),
            ],
        ),
    ]
